export interface BladeEntry {
  id: string
  zhName: string
  enName: string
  label: string
}

export const bladeList: BladeEntry[] = [
  { id: 'BX-01', zhName: '翔龍神劍', enName: 'DranSword', label: '[BX-01] 翔龍神劍 / DranSword' },
  { id: 'BX-02', zhName: '煉獄魔鐮', enName: 'HellsScythe', label: '[BX-02] 煉獄魔鐮 / HellsScythe' },
  { id: 'BX-03', zhName: '巫師弩箭', enName: 'WizardArrow', label: '[BX-03] 巫師弩箭 / WizardArrow' },
  { id: 'BX-04', zhName: '騎士護盾', enName: 'KnightShield', label: '[BX-04] 騎士護盾 / KnightShield' },
  { id: 'BX-05', zhName: '巫師弩箭', enName: 'WizardArrow', label: '[BX-05] 巫師弩箭 / WizardArrow' },
  { id: 'BX-06', zhName: '騎士護盾', enName: 'KnightShield', label: '[BX-06] 騎士護盾 / KnightShield' },
  { id: 'BX-07', zhName: '翔龍神劍 特別版', enName: 'DranSword Special Ver.', label: '[BX-07] 翔龍神劍 特別版 / DranSword Special Ver.' },
  { id: 'BX-08-01', zhName: '煉獄魔鐮', enName: 'HellsScythe', label: '[BX-08-01] 煉獄魔鐮 / HellsScythe' },
  { id: 'BX-08-02', zhName: '騎士護盾', enName: 'KnightShield', label: '[BX-08-02] 騎士護盾 / KnightShield' },
  { id: 'BX-08-03', zhName: '巫師弩箭', enName: 'WizardArrow', label: '[BX-08-03] 巫師弩箭 / WizardArrow' },
  { id: 'BX-13', zhName: '騎士長槍', enName: 'KnightLance', label: '[BX-13] 騎士長槍 / KnightLance' },
  { id: 'BX-14-01', zhName: '烈鯊利刃', enName: 'SharkEdge', label: '[BX-14-01] 烈鯊利刃 / SharkEdge' },
  { id: 'BX-14-02', zhName: '烈鯊利刃', enName: 'SharkEdge', label: '[BX-14-02] 烈鯊利刃 / SharkEdge' },
  { id: 'BX-14-03', zhName: '翔龍神劍', enName: 'DranSword', label: '[BX-14-03] 翔龍神劍 / DranSword' },
  { id: 'BX-14-04', zhName: '煉獄魔鐮', enName: 'HellsScythe', label: '[BX-14-04] 煉獄魔鐮 / HellsScythe' },
  { id: 'BX-14-05', zhName: '騎士護盾', enName: 'KnightShield', label: '[BX-14-05] 騎士護盾 / KnightShield' },
  { id: 'BX-14-06', zhName: '巫師弩箭', enName: 'WizardArrow', label: '[BX-14-06] 巫師弩箭 / WizardArrow' },
  { id: 'BX-15', zhName: '獅王銳爪', enName: 'LeonClaw', label: '[BX-15] 獅王銳爪 / LeonClaw' },
  { id: 'BX-16-01', zhName: '毒蛇靈尾', enName: 'ViperTail', label: '[BX-16-01] 毒蛇靈尾 / ViperTail' },
  { id: 'BX-16-02', zhName: '毒蛇靈尾', enName: 'ViperTail', label: '[BX-16-02] 毒蛇靈尾 / ViperTail' },
  { id: 'BX-16-03', zhName: '毒蛇靈尾', enName: 'ViperTail', label: '[BX-16-03] 毒蛇靈尾 / ViperTail' },
  { id: 'BX-17-01', zhName: '翔龍神劍 紅色版', enName: 'DranSword Red Ver.', label: '[BX-17-01] 翔龍神劍 紅色版 / DranSword Red Ver.' },
  { id: 'BX-17-02', zhName: '巫師弩箭 藍色版', enName: 'WizardArrow Blue Ver.', label: '[BX-17-02] 巫師弩箭 藍色版 / WizardArrow Blue Ver.' },
  { id: 'BX-19', zhName: '犀牛號角', enName: 'RhinoHorn', label: '[BX-19] 犀牛號角 / RhinoHorn' },
  { id: 'BX-20-01', zhName: '翔龍雙刃', enName: 'DranDagger', label: '[BX-20-01] 翔龍雙刃 / DranDagger' },
  { id: 'BX-20-02', zhName: '烈鯊利刃', enName: 'SharkEdge', label: '[BX-20-02] 烈鯊利刃 / SharkEdge' },
  { id: 'BX-20-03', zhName: '騎士護盾', enName: 'KnightShield', label: '[BX-20-03] 騎士護盾 / KnightShield' },
  { id: 'BX-21-01', zhName: '煉獄鎖鏈', enName: 'HellsChain', label: '[BX-21-01] 煉獄鎖鏈 / HellsChain' },
  { id: 'BX-21-02', zhName: '騎士長槍', enName: 'KnightLance', label: '[BX-21-02] 騎士長槍 / KnightLance' },
  { id: 'BX-21-03', zhName: '巫師弩箭', enName: 'WizardArrow', label: '[BX-21-03] 巫師弩箭 / WizardArrow' },
  { id: 'BX-22', zhName: '翔龍神劍', enName: 'DranSword', label: '[BX-22] 翔龍神劍 / DranSword' },
  { id: 'BX-23', zhName: '鳳凰飛翼 金屬塗層：紅色', enName: 'PhoenixWing (Metal Coat: Red)', label: '[BX-23] 鳳凰飛翼 金屬塗層：紅色 / PhoenixWing (Metal Coat: Red)' },
  { id: 'BX-24-01', zhName: '飛龍狂風', enName: 'WyvernGale', label: '[BX-24-01] 飛龍狂風 / WyvernGale' },
  { id: 'BX-24-02', zhName: '飛龍狂風', enName: 'WyvernGale', label: '[BX-24-02] 飛龍狂風 / WyvernGale' },
  { id: 'BX-24-03', zhName: '騎士長槍', enName: 'KnightLance', label: '[BX-24-03] 騎士長槍 / KnightLance' },
  { id: 'BX-24-04', zhName: '毒蛇靈尾', enName: 'ViperTail', label: '[BX-24-04] 毒蛇靈尾 / ViperTail' },
  { id: 'BX-24-05', zhName: '獅王銳爪', enName: 'LeonClaw', label: '[BX-24-05] 獅王銳爪 / LeonClaw' },
  { id: 'BX-24-06', zhName: '巫師弩箭', enName: 'WizardArrow', label: '[BX-24-06] 巫師弩箭 / WizardArrow' },
  { id: 'BX-26', zhName: '獨角螫刺', enName: 'UnicornSting', label: '[BX-26] 獨角螫刺 / UnicornSting' },
  { id: 'BX-27-01', zhName: '史芬克斯斗篷', enName: 'SphinxCowl', label: '[BX-27-01] 史芬克斯斗篷 / SphinxCowl' },
  { id: 'BX-27-02', zhName: '史芬克斯斗篷', enName: 'SphinxCowl', label: '[BX-27-02] 史芬克斯斗篷 / SphinxCowl' },
  { id: 'BX-27-03', zhName: '史芬克斯斗篷', enName: 'SphinxCowl', label: '[BX-27-03] 史芬克斯斗篷 / SphinxCowl' },
  { id: 'BX-31-01', zhName: '暴龍節拍', enName: 'TyrannoBeat', label: '[BX-31-01] 暴龍節拍 / TyrannoBeat' },
  { id: 'BX-31-02', zhName: '暴龍節拍', enName: 'TyrannoBeat', label: '[BX-31-02] 暴龍節拍 / TyrannoBeat' },
  { id: 'BX-31-03', zhName: '煉獄鎖鏈', enName: 'HellsChain', label: '[BX-31-03] 煉獄鎖鏈 / HellsChain' },
  { id: 'BX-31-04', zhName: '翔龍雙刃', enName: 'DranDagger', label: '[BX-31-04] 翔龍雙刃 / DranDagger' },
  { id: 'BX-31-05', zhName: '烈鯊利刃', enName: 'SharkEdge', label: '[BX-31-05] 烈鯊利刃 / SharkEdge' },
  { id: 'BX-31-06', zhName: '犀牛號角', enName: 'RhinoHorn', label: '[BX-31-06] 犀牛號角 / RhinoHorn' },
  { id: 'BX-33', zhName: '純白猛虎', enName: 'WeissTiger', label: '[BX-33] 純白猛虎 / WeissTiger' },
  { id: 'BX-34', zhName: '鈷藍青龍', enName: 'CobaltDragoon', label: '[BX-34] 鈷藍青龍 / CobaltDragoon' },
  { id: 'BX-35-01', zhName: '漆黑護殼', enName: 'BlackShell', label: '[BX-35-01] 漆黑護殼 / BlackShell' },
  { id: 'BX-35-02', zhName: '漆黑護殼', enName: 'BlackShell', label: '[BX-35-02] 漆黑護殼 / BlackShell' },
  { id: 'BX-35-03', zhName: '獨角螫刺', enName: 'UnicornSting', label: '[BX-35-03] 獨角螫刺 / UnicornSting' },
  { id: 'BX-35-04', zhName: '巫師幻棍', enName: 'WizardRod', label: '[BX-35-04] 巫師幻棍 / WizardRod' },
  { id: 'BX-35-05', zhName: '鳳凰飛翼', enName: 'PhoenixWing', label: '[BX-35-05] 鳳凰飛翼 / PhoenixWing' },
  { id: 'BX-35-06', zhName: '毒蛇靈尾', enName: 'ViperTail', label: '[BX-35-06] 毒蛇靈尾 / ViperTail' },
  { id: 'BX-36-01', zhName: '戰鯨波浪', enName: 'WhaleWave', label: '[BX-36-01] 戰鯨波浪 / WhaleWave' },
  { id: 'BX-36-02', zhName: '戰鯨波浪', enName: 'WhaleWave', label: '[BX-36-02] 戰鯨波浪 / WhaleWave' },
  { id: 'BX-36-03', zhName: '戰鯨波浪', enName: 'WhaleWave', label: '[BX-36-03] 戰鯨波浪 / WhaleWave' },
  { id: 'BX-37', zhName: '狂熊銳爪', enName: 'BearScratch', label: '[BX-37] 狂熊銳爪 / BearScratch' },
  { id: 'BX-38', zhName: '緋紅迦樓羅', enName: 'CrimsonGaruda', label: '[BX-38] 緋紅迦樓羅 / CrimsonGaruda' },
  { id: 'BX-39-01', zhName: '神護魔龍', enName: 'LeonCrest', label: '[BX-39-01] 神護魔龍 / LeonCrest' },
  { id: 'BX-39-02', zhName: '神護魔龍', enName: 'LeonCrest', label: '[BX-39-02] 神護魔龍 / LeonCrest' },
  { id: 'BX-39-03', zhName: '神護魔龍', enName: 'LeonCrest', label: '[BX-39-03] 神護魔龍 / LeonCrest' },
  { id: 'BX-44', zhName: '三角龍壓', enName: 'TriceraPhalanx', label: '[BX-44] 三角龍壓 / TriceraPhalanx' },
  { id: 'BX-45', zhName: '武士聖劍', enName: 'SamuraiSaber', label: '[BX-45] 武士聖劍 / SamuraiSaber' },
  { id: 'BX-46-01', zhName: '鈷藍魔龍 金屬塗層：紅色', enName: 'CobaltDrake (Metal Coat: Red)', label: '[BX-46-01] 鈷藍魔龍 金屬塗層：紅色 / CobaltDrake (Metal Coat: Red)' },
  { id: 'BX-46-02', zhName: '凶羊截擊', enName: 'AriesReck', label: '[BX-46-02] 凶羊截擊 / AriesReck' },
  { id: 'BX-48-01', zhName: '鈷藍青龍 金屬塗層：黑色', enName: 'CobaltDragoon (Metal Coat: Black)', label: '[BX-48-01] 鈷藍青龍 金屬塗層：黑色 / CobaltDragoon (Metal Coat: Black)' },
  { id: 'BX-48-02', zhName: '烈鯊利刃 金屬塗層：藍色', enName: 'SharkEdge (Metal Coat: Blue)', label: '[BX-48-02] 烈鯊利刃 金屬塗層：藍色 / SharkEdge (Metal Coat: Blue)' },
  { id: 'BX-48-03', zhName: '狂象長牙 金屬塗層：黑色', enName: 'MammothTusk (Metal Coat: Black)', label: '[BX-48-03] 狂象長牙 金屬塗層：黑色 / MammothTusk (Metal Coat: Black)' },
  { id: 'BX-48-04', zhName: '煉獄魔鐮 金屬塗層：金色', enName: 'HellsScythe (Metal Coat: Gold)', label: '[BX-48-04] 煉獄魔鐮 金屬塗層：金色 / HellsScythe (Metal Coat: Gold)' },
  { id: 'BX-48-05', zhName: '翔龍破壞劍 金屬塗層：紅色', enName: 'DranBuster (Metal Coat: Red)', label: '[BX-48-05] 翔龍破壞劍 金屬塗層：紅色 / DranBuster (Metal Coat: Red)' },
  { id: 'BX-49', zhName: '翔龍突擊', enName: 'DranSword (Impact Ver.)', label: '[BX-49] 翔龍突擊 / DranSword (Impact Ver.)' },
  { id: 'BXC-00-01', zhName: '翔龍神劍 金屬塗層：金色', enName: 'DranSword (Metal Coat: Gold)', label: '[BXC-00-01] 翔龍神劍 金屬塗層：金色 / DranSword (Metal Coat: Gold)' },
  { id: 'BXC-00-02', zhName: '翔龍神劍 金屬塗層：銀色', enName: 'DranSword (Metal Coat: Silver)', label: '[BXC-00-02] 翔龍神劍 金屬塗層：銀色 / DranSword (Metal Coat: Silver)' },
  { id: 'BXC-00-03', zhName: '翔龍神劍 金屬塗層：銅色', enName: 'DranSword (Metal Coat: Bronze)', label: '[BXC-00-03] 翔龍神劍 金屬塗層：銅色 / DranSword (Metal Coat: Bronze)' },
  { id: 'BXG-01', zhName: '朱雀戰神', enName: 'DranzerSpiral', label: '[BXG-01] 朱雀戰神 / DranzerSpiral' },
  { id: 'BXG-03', zhName: '煉獄魔鐮 金屬塗層：金色', enName: 'HellsScythe (Metal Coat: Gold)', label: '[BXG-03] 煉獄魔鐮 金屬塗層：金色 / HellsScythe (Metal Coat: Gold)' },
  { id: 'BXG-04', zhName: '青翼白虎', enName: 'DrigerSlash', label: '[BXG-04] 青翼白虎 / DrigerSlash' },
  { id: 'BXG-05', zhName: '獅王銳爪 金屬塗層：金色', enName: 'LeonClaw (Metal Coat: Gold)', label: '[BXG-05] 獅王銳爪 金屬塗層：金色 / LeonClaw (Metal Coat: Gold)' },
  { id: 'BXG-06', zhName: '烈鯊利刃 金屬塗層：藍色', enName: 'SharkEdge (Metal Coat: Blue)', label: '[BXG-06] 烈鯊利刃 金屬塗層：藍色 / SharkEdge (Metal Coat: Blue)' },
  { id: 'BXG-07', zhName: '雷霆魔龍 (昇擊型)', enName: 'L-Drago (Upper Type)', label: '[BXG-07] 雷霆魔龍 (昇擊型) / L-Drago (Upper Type)' },
  { id: 'BXG-07', zhName: '雷霆魔龍 (連擊型)', enName: 'L-Drago (Continuity Type)', label: '[BXG-07] 雷霆魔龍 (連擊型) / L-Drago (Continuity Type)' },
  { id: 'BXG-08', zhName: '煉獄鎖鍊 金屬塗層：黑色', enName: 'HellsChain (Metal Coat: Black)', label: '[BXG-08] 煉獄鎖鍊 金屬塗層：黑色 / HellsChain (Metal Coat: Black)' },
  { id: 'BXG-09', zhName: '鈷藍青龍 金屬塗層：黑色', enName: 'CobaltDragoon (Metal Coat: Black)', label: '[BXG-09] 鈷藍青龍 金屬塗層：黑色 / CobaltDragoon (Metal Coat: Black)' },
  { id: 'BXG-11', zhName: '青銅玄武', enName: 'DracielShield', label: '[BXG-11] 青銅玄武 / DracielShield' },
  { id: 'BXG-12', zhName: '暴風戰龍', enName: 'StormPegasus', label: '[BXG-12] 暴風戰龍 / StormPegasus' },
  { id: 'BXG-12', zhName: '烈風天馬', enName: 'RayGil', label: '[BXG-12] 烈風天馬 / RayGil' },
  { id: 'BXG-12', zhName: '勝利武神', enName: 'VictoryValkyrie', label: '[BXG-12] 勝利武神 / VictoryValkyrie' },
  { id: 'BXG-12', zhName: '翔龍神劍 彩光貼紙版', enName: 'DranSword (Hologram Sticker Ver.)', label: '[BXG-12] 翔龍神劍 彩光貼紙版 / DranSword (Hologram Sticker Ver.)' },
  { id: 'BXG-13', zhName: '異界聖劍', enName: 'XyliphosSword', label: '[BXG-13] 異界聖劍 / XyliphosSword' },
  { id: 'BXG-15', zhName: '朱雀戰神 黑色版', enName: 'DranzerSpiral Black Ver.', label: '[BXG-15] 朱雀戰神 黑色版 / DranzerSpiral Black Ver.' },
  { id: 'BXG-18', zhName: '翔龍破壞劍 金屬塗層：藍色 FC巴塞隆拿版', enName: 'DranBuster (Metal Coat: Blue) FC Barcelona Ver.', label: '[BXG-18] 翔龍破壞劍 金屬塗層：藍色 FC巴塞隆拿版 / DranBuster (Metal Coat: Blue) FC Barcelona Ver.' },
  { id: 'BXG-19', zhName: '煉獄惡鎚 金屬塗層：紅色 FC巴塞隆拿版', enName: 'HellsHammer (Metal Coat: Red) FC Barcelona Ver.', label: '[BXG-19] 煉獄惡鎚 金屬塗層：紅色 FC巴塞隆拿版 / HellsHammer (Metal Coat: Red) FC Barcelona Ver.' },
  { id: 'BXG-20', zhName: '岩巖獅王', enName: 'RockLeone', label: '[BXG-20] 岩巖獅王 / RockLeone' },
  { id: 'BXG-21', zhName: '暴風巨神', enName: 'StormSpriggan', label: '[BXG-21] 暴風巨神 / StormSpriggan' },
  { id: 'BXG-22', zhName: '暴風戰龍', enName: 'StormPegasus', label: '[BXG-22] 暴風戰龍 / StormPegasus' },
  { id: 'BXG-23', zhName: '鈷藍魔龍 透明版', enName: 'CobaltDrake Transparent Ver.', label: '[BXG-23] 鈷藍魔龍 透明版 / CobaltDrake Transparent Ver.' },
  { id: 'BXG-24', zhName: '翔空天馬 紅色版', enName: 'SkyPegasus Red Ver.', label: '[BXG-24] 翔空天馬 紅色版 / SkyPegasus Red Ver.' },
  { id: 'BXG-25', zhName: '翔龍神劍 金屬塗層：白色', enName: 'DranSword (Metal Coat: White)', label: '[BXG-25] 翔龍神劍 金屬塗層：白色 / DranSword (Metal Coat: White)' },
  { id: 'BXG-25', zhName: '翔龍雙刃 金屬塗層：白色', enName: 'DranDagger (Metal Coat: White)', label: '[BXG-25] 翔龍雙刃 金屬塗層：白色 / DranDagger (Metal Coat: White)' },
  { id: 'BXG-25', zhName: '翔龍破壞劍 金屬塗層:白色', enName: 'DranBuster (Metal Coat: White)', label: '[BXG-25] 翔龍破壞劍 金屬塗層:白色 / DranBuster (Metal Coat: White)' },
  { id: 'BXG-32', zhName: '狂象長牙 金屬塗層：黑色', enName: 'MammothTusk (Metal Coat: Black)', label: '[BXG-32] 狂象長牙 金屬塗層：黑色 / MammothTusk (Metal Coat: Black)' },
  { id: 'BXG-42', zhName: '騎士護甲 金屬塗層：海藍色', enName: 'KnightMail (Metal Coat: Marine Blue)', label: '[BXG-42] 騎士護甲 金屬塗層：海藍色 / KnightMail (Metal Coat: Marine Blue)' },
  { id: 'BXG-43', zhName: '巫師弧光R 金屬塗層：黑色', enName: 'WizardArc R (Metal Coat: Black)', label: '[BXG-43] 巫師弧光R 金屬塗層：黑色 / WizardArc R (Metal Coat: Black)' },
  { id: 'BXG-45', zhName: '天馬轟裂A 金屬塗層：紅色', enName: 'PegasusBlast A (Metal Coat: Red)', label: '[BXG-45] 天馬轟裂A 金屬塗層：紅色 / PegasusBlast A (Metal Coat: Red)' },
  { id: 'BXH-01', zhName: '鈷藍魔龍 金屬塗層：藍色', enName: 'CobaltDrake (Metal Coat: Blue)', label: '[BXH-01] 鈷藍魔龍 金屬塗層：藍色 / CobaltDrake (Metal Coat: Blue)' },
  { id: 'BXH-02', zhName: '騎士護盾 金屬塗層：金色', enName: 'KnightShield (Metal Coat: Gold)', label: '[BXH-02] 騎士護盾 金屬塗層：金色 / KnightShield (Metal Coat: Gold)' },
  { id: 'BXH-09', zhName: '巫師幻棍 金屬塗層：金色', enName: 'WizardRod (Metal Coat: Gold)', label: '[BXH-09] 巫師幻棍 金屬塗層：金色 / WizardRod (Metal Coat: Gold)' },
  { id: 'BXH-10', zhName: '翔空天馬 金屬塗層：雙層', enName: 'SkyPegasus (Metal Coat: Dual Layer)', label: '[BXH-10] 翔空天馬 金屬塗層：雙層 / SkyPegasus (Metal Coat: Dual Layer)' },
  { id: 'BXH-14', zhName: '戰神雷動S 金屬塗層：金色', enName: 'MarsThunder S (Metal Coat: Gold)', label: '[BXH-14] 戰神雷動S 金屬塗層：金色 / MarsThunder S (Metal Coat: Gold)' },
  { id: 'BXH-15', zhName: '英仙幽暗B 金屬塗層：金色', enName: 'PerseusGloom B (Metal Coat: Gold)', label: '[BXH-15] 英仙幽暗B 金屬塗層：金色 / PerseusGloom B (Metal Coat: Gold)' },
  { id: 'BXH-16', zhName: '翔龍勇者S 金屬塗層：金色', enName: 'DranBrave S (Metal Coat: Gold)', label: '[BXH-16] 翔龍勇者S 金屬塗層：金色 / DranBrave S (Metal Coat: Gold)' },
  { id: 'BXH-16', zhName: '翔龍勇者S 金屬塗層：銀色', enName: 'DranBrave S (Metal Coat: Silver)', label: '[BXH-16] 翔龍勇者S 金屬塗層：銀色 / DranBrave S (Metal Coat: Silver)' },
  { id: 'BXH-16', zhName: '翔龍勇者S 金屬塗層：銅色', enName: 'DranBrave S (Metal Coat: Bronze)', label: '[BXH-16] 翔龍勇者S 金屬塗層：銅色 / DranBrave S (Metal Coat: Bronze)' },
  { id: 'CX-01', zhName: '翔龍勇者S', enName: 'DranBrave S', label: '[CX-01] 翔龍勇者S / DranBrave S' },
  { id: 'CX-02', zhName: '巫師弧光R', enName: 'WizardArc R', label: '[CX-02] 巫師弧光R / WizardArc R' },
  { id: 'CX-03', zhName: '英仙幽暗B', enName: 'PerseusGloom B', label: '[CX-03] 英仙幽暗B / PerseusGloom B' },
  { id: 'CX-04', zhName: '翔龍勇者S 特別版', enName: 'DranBrave S Special Ver.', label: '[CX-04] 翔龍勇者S 特別版 / DranBrave S Special Ver.' },
  { id: 'CX-04', zhName: '英仙幽暗B 特別版', enName: 'PerseusGloom B Special Ver.', label: '[CX-04] 英仙幽暗B 特別版 / PerseusGloom B Special Ver.' },
  { id: 'CX-05-01', zhName: '煉獄死神T', enName: 'HellsDeath T', label: '[CX-05-01] 煉獄死神T / HellsDeath T' },
  { id: 'CX-05-02', zhName: '犀牛死神C', enName: 'RhinoDeath C', label: '[CX-05-02] 犀牛死神C / RhinoDeath C' },
  { id: 'CX-05-03', zhName: '煉獄弧光T', enName: 'HellsArc T', label: '[CX-05-03] 煉獄弧光T / HellsArc T' },
  { id: 'CX-05-04', zhName: '獅王徽章', enName: 'LeonCrest', label: '[CX-05-04] 獅王徽章 / LeonCrest' },
  { id: 'CX-05-05', zhName: '鳳凰炎舵', enName: 'PhoenixRudder', label: '[CX-05-05] 鳳凰炎舵 / PhoenixRudder' },
  { id: 'CX-05-06', zhName: '戰鯨波浪', enName: 'WhaleWave', label: '[CX-05-06] 戰鯨波浪 / WhaleWave' },
  { id: 'CX-06-01', zhName: '妖狐兇尾J', enName: 'NineTails J', label: '[CX-06-01] 妖狐兇尾J / NineTails J' },
  { id: 'CX-06-02', zhName: '妖狐兇尾J', enName: 'NineTails J', label: '[CX-06-02] 妖狐兇尾J / NineTails J' },
  { id: 'CX-06-03', zhName: '妖狐兇尾J', enName: 'NineTails J', label: '[CX-06-03] 妖狐兇尾J / NineTails J' },
  { id: 'CX-07', zhName: '天馬轟裂A', enName: 'PegasusBlast A', label: '[CX-07] 天馬轟裂A / PegasusBlast A' },
  { id: 'CX-08-01', zhName: '地獄犬烈焰W', enName: 'CerberusBlaze W', label: '[CX-08-01] 地獄犬烈焰W / CerberusBlaze W' },
  { id: 'CX-08-02', zhName: '戰鯨烈焰M', enName: 'WhaleBlaze M', label: '[CX-08-02] 戰鯨烈焰M / WhaleBlaze M' },
  { id: 'CX-08-03', zhName: '地獄犬幽暗W', enName: 'CerberusGloom W', label: '[CX-08-03] 地獄犬幽暗W / CerberusGloom W' },
  { id: 'CX-08-04', zhName: '翔龍破壞劍', enName: 'DranBuster', label: '[CX-08-04] 翔龍破壞劍 / DranBuster' },
  { id: 'CX-08-05', zhName: '漆黑護殼', enName: 'BlackShell', label: '[CX-08-05] 漆黑護殼 / BlackShell' },
  { id: 'CX-08-06', zhName: '鈷藍青龍', enName: 'CobaltDragoon', label: '[CX-08-06] 鈷藍青龍 / CobaltDragoon' },
  { id: 'CX-09', zhName: '天陽光噬D', enName: 'SolFlare D', label: '[CX-09] 天陽光噬D / SolFlare D' },
  { id: 'CX-10', zhName: '戰狼狩獵F', enName: 'WolfHunt F', label: '[CX-10] 戰狼狩獵F / WolfHunt F' },
  { id: 'CX-11-01', zhName: '帝皇霸權H', enName: 'KaiserDomination H', label: '[CX-11-01] 帝皇霸權H / KaiserDomination H' },
  { id: 'CX-11-02', zhName: '魔像巨石 金屬塗層：綠色', enName: 'GolemRock (Metal Coat: Green)', label: '[CX-11-02] 魔像巨石 金屬塗層：綠色 / GolemRock (Metal Coat: Green)' },
  { id: 'CX-11-03', zhName: '烈鯊鰓刃', enName: 'SharkGill', label: '[CX-11-03] 烈鯊鰓刃 / SharkGill' },
  { id: 'CX-12', zhName: '鳳凰炎光Z', enName: 'PhoenixFlare Z', label: '[CX-12] 鳳凰炎光Z / PhoenixFlare Z' },
  { id: 'CX-13', zhName: '龍王閃擊BK', enName: 'L-DragoBlitz BK', label: '[CX-13] 龍王閃擊BK / L-DragoBlitz BK' },
  { id: 'CX-14', zhName: '騎士堡壘GV', enName: 'KnightFortress GV', label: '[CX-14] 騎士堡壘GV / KnightFortress GV' },
  { id: 'CX-15', zhName: '邪神狂怒FE', enName: 'BeelzebubFury FE', label: '[CX-15] 邪神狂怒FE / BeelzebubFury FE' },
  { id: 'CX-17-01', zhName: '獨角三極PO', enName: 'UnicornTri PO', label: '[CX-17-01] 獨角三極PO / UnicornTri PO' },
  { id: 'CX-17-02', zhName: '獨角三極PO', enName: 'UnicornTri PO', label: '[CX-17-02] 獨角三極PO / UnicornTri PO' },
  { id: 'CX-17-03', zhName: '武士之刃', enName: 'SamuraiBlade', label: '[CX-17-03] 武士之刃 / SamuraiBlade' },
  { id: 'CX-17-04', zhName: '煉獄惡鎚', enName: 'HellsHammer', label: '[CX-17-04] 煉獄惡鎚 / HellsHammer' },
  { id: 'CX-17-05', zhName: '暴龍節拍', enName: 'TyrannoBeat', label: '[CX-17-05] 暴龍節拍 / TyrannoBeat' },
  { id: 'CX-17-06', zhName: '緋紅迦樓羅', enName: 'CrimsonGaruda', label: '[CX-17-06] 緋紅迦樓羅 / CrimsonGaruda' },
  { id: 'UX-01', zhName: '翔龍破壞劍', enName: 'DranBuster', label: '[UX-01] 翔龍破壞劍 / DranBuster' },
  { id: 'UX-02', zhName: '煉獄惡鎚', enName: 'HellsHammer', label: '[UX-02] 煉獄惡鎚 / HellsHammer' },
  { id: 'UX-03', zhName: '巫師幻棍', enName: 'WizardRod', label: '[UX-03] 巫師幻棍 / WizardRod' },
  { id: 'UX-04-01', zhName: '翔龍破壞劍 特別版', enName: 'DranBuster Special Ver.', label: '[UX-04-01] 翔龍破壞劍 特別版 / DranBuster Special Ver.' },
  { id: 'UX-04-02', zhName: '巫師幻棍 特別版', enName: 'WizardRod Special Ver.', label: '[UX-04-02] 巫師幻棍 特別版 / WizardRod Special Ver.' },
  { id: 'UX-05-01', zhName: '忍者幻影', enName: 'ShinobiShadow', label: '[UX-05-01] 忍者幻影 / ShinobiShadow' },
  { id: 'UX-05-02', zhName: '忍者幻影', enName: 'ShinobiShadow', label: '[UX-05-02] 忍者幻影 / ShinobiShadow' },
  { id: 'UX-05-03', zhName: '忍者幻影', enName: 'ShinobiShadow', label: '[UX-05-03] 忍者幻影 / ShinobiShadow' },
  { id: 'UX-06', zhName: '獅王徽章', enName: 'LeonCrest', label: '[UX-06] 獅王徽章 / LeonCrest' },
  { id: 'UX-07-01', zhName: '鳳凰炎舵 金屬塗層：紅色', enName: 'PhoenixRudder (Metal Coat: Red)', label: '[UX-07-01] 鳳凰炎舵 金屬塗層：紅色 / PhoenixRudder (Metal Coat: Red)' },
  { id: 'UX-07-02', zhName: '飛龍狂風', enName: 'WyvernGale', label: '[UX-07-02] 飛龍狂風 / WyvernGale' },
  { id: 'UX-07-03', zhName: '史芬克斯斗篷', enName: 'SphinxCowl', label: '[UX-07-03] 史芬克斯斗篷 / SphinxCowl' },
  { id: 'UX-08', zhName: '白銀戰狼', enName: 'SilverWolf', label: '[UX-08] 白銀戰狼 / SilverWolf' },
  { id: 'UX-09', zhName: '武士之刃', enName: 'SamuraiBlade', label: '[UX-09] 武士之刃 / SamuraiBlade' },
  { id: 'UX-10-01', zhName: '騎士護甲', enName: 'KnightMail', label: '[UX-10-01] 騎士護甲 / KnightMail' },
  { id: 'UX-10-02', zhName: '暴龍節拍 金屬塗層：紅色', enName: 'TyrannoBeat (Metal Coat: Red)', label: '[UX-10-02] 暴龍節拍 金屬塗層：紅色 / TyrannoBeat (Metal Coat: Red)' },
  { id: 'UX-10-03', zhName: '翼龍波動', enName: 'PteraSwing', label: '[UX-10-03] 翼龍波動 / PteraSwing' },
  { id: 'UX-10-04', zhName: '煉獄惡鎚 金屬塗層：藍色', enName: 'HellsHammer (Metal Coat: Blue)', label: '[UX-10-04] 煉獄惡鎚 金屬塗層：藍色 / HellsHammer (Metal Coat: Blue)' },
  { id: 'UX-11', zhName: '衝擊魔龍', enName: 'ImpactDrake', label: '[UX-11] 衝擊魔龍 / ImpactDrake' },
  { id: 'UX-12-01', zhName: '幽靈圓環', enName: 'GhostHoop', label: '[UX-12-01] 幽靈圓環 / GhostHoop' },
  { id: 'UX-12-02', zhName: '幽靈圓環', enName: 'GhostHoop', label: '[UX-12-02] 幽靈圓環 / GhostHoop' },
  { id: 'UX-12-03', zhName: '忍者幻影', enName: 'ShinobiShadow', label: '[UX-12-03] 忍者幻影 / ShinobiShadow' },
  { id: 'UX-12-04', zhName: '獅王銳爪', enName: 'LeonClaw', label: '[UX-12-04] 獅王銳爪 / LeonClaw' },
  { id: 'UX-12-05', zhName: '鳳凰炎羽', enName: 'PhoenixWing', label: '[UX-12-05] 鳳凰炎羽 / PhoenixWing' },
  { id: 'UX-12-06', zhName: '飛龍狂風', enName: 'WyvernGale', label: '[UX-12-06] 飛龍狂風 / WyvernGale' },
  { id: 'UX-13', zhName: '魔像巨石', enName: 'GolemRock', label: '[UX-13] 魔像巨石 / GolemRock' },
  { id: 'UX-14', zhName: '毒蠍刺槍', enName: 'ScorpioLance', label: '[UX-14] 毒蠍刺槍 / ScorpioLance' },
  { id: 'UX-15-01', zhName: '烈鯊鱗甲', enName: 'SharkScale', label: '[UX-15-01] 烈鯊鱗甲 / SharkScale' },
  { id: 'UX-15-02', zhName: '暴龍咆哮', enName: 'TyrannoRoar', label: '[UX-15-02] 暴龍咆哮 / TyrannoRoar' },
  { id: 'UX-15-03', zhName: '煉獄勇者J', enName: 'HellsBrave J', label: '[UX-15-03] 煉獄勇者J / HellsBrave J' },
  { id: 'UX-16-01', zhName: '時鐘幽景', enName: 'Horogeist', label: '[UX-16-01] 時鐘幽景 / Horogeist' },
  { id: 'UX-16-02', zhName: '時鐘幽景', enName: 'Horogeist', label: '[UX-16-02] 時鐘幽景 / Horogeist' },
  { id: 'UX-16-03', zhName: '時鐘幽景', enName: 'Horogeist', label: '[UX-16-03] 時鐘幽景 / Horogeist' },
  { id: 'UX-17', zhName: '隕石青龍 金屬塗層：白色', enName: 'MeteoDragoon (Metal Coat: White)', label: '[UX-17] 隕石青龍 金屬塗層：白色 / MeteoDragoon (Metal Coat: White)' },
  { id: 'UX-18-01', zhName: '木乃伊詛咒', enName: 'MummyCurse', label: '[UX-18-01] 木乃伊詛咒 / MummyCurse' },
  { id: 'UX-18-02', zhName: '木乃伊詛咒', enName: 'MummyCurse', label: '[UX-18-02] 木乃伊詛咒 / MummyCurse' },
  { id: 'UX-18-03', zhName: '天馬兇尾M', enName: 'PegasusTail M', label: '[UX-18-03] 天馬兇尾M / PegasusTail M' },
  { id: 'UX-18-04', zhName: '天陽勇者C', enName: 'SolBrave C', label: '[UX-18-04] 天陽勇者C / SolBrave C' },
  { id: 'UX-18-05', zhName: '翔龍雙刃', enName: 'DranDagger', label: '[UX-18-05] 翔龍雙刃 / DranDagger' },
  { id: 'UX-18-06', zhName: '純白猛虎', enName: 'WeissTiger', label: '[UX-18-06] 純白猛虎 / WeissTiger' },
  { id: 'UX-19', zhName: '彈丸獅鷲', enName: 'BulletGriffin', label: '[UX-19] 彈丸獅鷲 / BulletGriffin' },
]
